# Generated by Django 5.2.4 on 2026-01-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingsystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remainingamount',
            name='remaining_amount',
            field=models.IntegerField(default=0),
        ),
    ]
