# Generated by Django 5.2.4 on 2026-01-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingsystem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='expense_categories',
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='expense_categories', to='billingsystem.company'),
        ),
    ]
