# Generated by Django 5.2.4 on 2026-01-10 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billingsystem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentin',
            name='remainings',
        ),
    ]
