# Generated by Django 5.2.4 on 2026-01-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingsystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
