# Generated by Django 5.2.4 on 2026-01-10 12:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingsystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentin',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
