# Generated by Django 5.2.7 on 2025-11-30 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billingsystem", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=15)),
                ("address", models.TextField()),
                ("tax_id", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.AddField(
            model_name="orderlist",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("OWNER", "Company Owner"),
                    ("MANAGER", "Manager"),
                    ("STAFF", "Staff"),
                ],
                default="STAFF",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="customer",
            name="company",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customers",
                to="billingsystem.company",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderlist",
            name="company",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="billingsystem.company",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="company",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="billingsystem.company",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productcategory",
            name="company",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_categories",
                to="billingsystem.company",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employees",
                to="billingsystem.company",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="customer",
            unique_together={("company", "email")},
        ),
        migrations.AlterUniqueTogether(
            name="product",
            unique_together={("company", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="productcategory",
            unique_together={("company", "name")},
        ),
    ]
