# Generated by Django 5.2.4 on 2026-01-24 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingsystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalcharges',
            name='additional_charges',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='billingsystem.orderlist'),
        ),
    ]
