# Generated by Django 5.2.4 on 2025-12-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingsystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
