# Generated by Django 5.2.4 on 2026-01-26 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billingsystem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='bill_no',
        ),
    ]
