# Generated by Django 5.2.4 on 2026-01-14 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billingsystem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_opening_type',
        ),
    ]
