# Generated by Django 5.2.4 on 2026-01-09 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billingsystem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remainingamount',
            old_name='order',
            new_name='orders',
        ),
    ]
