# Generated by Django 5.2.4 on 2025-12-31 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingsystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150)),
                ('date', models.DateField(auto_now=True)),
                ('change', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('remarks', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='orderlist',
            name='item_acitivity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orderactivities', to='billingsystem.itemactivity'),
        ),
        migrations.AddField(
            model_name='product',
            name='item_acitivity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='billingsystem.itemactivity'),
        ),
    ]
