# Generated by Django 5.2.7 on 2025-11-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billingsystem", "0002_alter_customer_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Books",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("books_cat", models.CharField(max_length=100)),
                ("author_name", models.CharField(max_length=100)),
            ],
        ),
    ]
