# Generated by Django 5.2.4 on 2026-01-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingsystem', '0002_alter_remainingamount_remaining_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remainingamount',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
