# Generated by Django 5.2.4 on 2026-01-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingsystem', '0002_alter_paymentin_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentin',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
