# Generated by Django 5.2.4 on 2026-01-15 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingsystem', '0002_customer_customer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanceadjustment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customerBalanceAdjustment', to='billingsystem.customer'),
        ),
    ]
