# Generated by Django 5.2.4 on 2026-01-26 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingsystem', '0002_remove_purchase_amount_remove_purchase_bill_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemactivity',
            name='purchase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchaseactivities', to='billingsystem.purchase'),
        ),
        migrations.AlterField(
            model_name='itemactivity',
            name='remarks',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
