# Generated by Django 5.2.7 on 2025-12-31 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billingsystem", "0002_itemactivity_orderlist_item_acitivity_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="itemactivity",
            name="type",
        ),
        migrations.RemoveField(
            model_name="orderlist",
            name="item_acitivity",
        ),
        migrations.RemoveField(
            model_name="product",
            name="item_acitivity",
        ),
        migrations.AddField(
            model_name="itemactivity",
            name="order",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orderactivities",
                to="billingsystem.orderlist",
            ),
        ),
        migrations.AddField(
            model_name="itemactivity",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="activities",
                to="billingsystem.product",
            ),
        ),
    ]
