# Generated by Django 5.2.4 on 2025-12-18 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billingsystem', '0002_orderlist_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remainingamount',
            old_name='customer',
            new_name='customero',
        ),
    ]
