# Generated by Django 5.2.4 on 2025-11-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingsystem', '0002_alter_customer_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='cost_price',
        ),
        migrations.AddField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
