# Generated by Django 5.2.4 on 2026-01-24 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingsystem', '0002_alter_additionalcharges_additional_charges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='bill_list',
        ),
        migrations.AddField(
            model_name='bill',
            name='purchase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='billingsystem.purchase'),
        ),
        migrations.AlterField(
            model_name='ordersummary',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='billingsystem.orderlist'),
        ),
    ]
