# Generated by Django 5.2.7 on 2025-12-01 12:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "billingsystem",
            "0002_company_alter_user_options_orderlist_created_by_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AddField(
            model_name="company",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="company",
            name="plan",
            field=models.CharField(
                choices=[("free", "Free"), ("basic", "Basic"), ("pro", "Professional")],
                default="free",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="subdomain",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="user",
            name="gmail",
            field=models.EmailField(
                blank=True, max_length=255, null=True, verbose_name="Gmail Address"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="user",
            unique_together={("company", "username")},
        ),
    ]
