# Generated by Django 5.2.4 on 2025-12-01 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billingsystem', '0002_alter_userregistration_phone_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistration',
            name='company_name',
        ),
    ]
