# Generated by Django 5.2.4 on 2025-12-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingsystem', '0002_orderlist_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersummary',
            name='additional_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ordersummary',
            name='received_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
