# Generated by Django 5.2.4 on 2026-01-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingsystem', '0003_alter_paymentin_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
