# Generated by Django 5.2.4 on 2025-12-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingsystem', '0003_remove_userregistration_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
