# Generated by Django 5.2.7 on 2025-11-24 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billingsystem", "0003_books"),
        ("billingsystem", "0003_rename_price_product_cost_price_and_more"),
    ]

    operations = []
