# Generated by Django 5.2.4 on 2026-01-09 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingsystem', '0003_alter_remainingamount_remaining_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remainingamount',
            name='orders',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remaining', to='billingsystem.orderlist'),
        ),
    ]
