# Generated by Django 5.2.4 on 2025-12-18 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billingsystem', '0003_rename_customer_remainingamount_customero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remainingamount',
            old_name='customero',
            new_name='customer',
        ),
    ]
