# Generated by Django 5.2.4 on 2025-12-15 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingsystem', '0003_ordersummary_additional_charges_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersummary',
            name='additional_charges',
        ),
        migrations.CreateModel(
            name='AdditionalCharges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_name', models.CharField(max_length=200)),
                ('additional_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('additional_charges', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='billingsystem.orderlist')),
            ],
        ),
    ]
