# Generated by Django 5.2.4 on 2026-01-01 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingsystem', '0003_remove_itemactivity_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemactivity',
            name='change',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='itemactivity',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderactivities', to='billingsystem.orderlist'),
        ),
    ]
