# Generated by Django 5.2.4 on 2026-01-24 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingsystem', '0003_remove_purchase_bill_list_bill_purchase_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='additional_charge',
        ),
        migrations.AddField(
            model_name='additionalcharges',
            name='purchase_additional_charges',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_charges', to='billingsystem.purchase'),
        ),
        migrations.AlterField(
            model_name='additionalcharges',
            name='additional_charges',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges', to='billingsystem.orderlist'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='remaining',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remainingafterpurchase', to='billingsystem.remainingamount'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='summary',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchaseordersumarry', to='billingsystem.ordersummary'),
        ),
    ]
