# Generated by Django 5.2.4 on 2026-01-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingsystem', '0003_alter_balanceadjustment_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='opening_type',
            field=models.CharField(choices=[('TORECEIVE', 'To Receive'), ('TOGIVE', 'To Give')], default='TORECEIVE', max_length=10),
        ),
    ]
