# Generated by Django 5.2.4 on 2026-01-26 10:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingsystem', '0003_itemactivity_purchase_alter_itemactivity_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
