# Generated by Django 5.2.4 on 2026-01-12 08:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingsystem', '0004_alter_orderlist_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='order_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='PaymentOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('payment_out', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('remarks', models.CharField(max_length=200)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paymentOut', to='billingsystem.customer')),
                ('remainings', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paymentOutRemaining', to='billingsystem.remainingamount')),
            ],
        ),
    ]
