# Generated by Django 5.2.7 on 2025-12-02 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "billingsystem",
            "0004_alter_user_options_alter_user_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderlist",
            name="invoice_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderlist",
            name="is_simple_invoice",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="bill",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bills",
                to="billingsystem.product",
            ),
        ),
    ]
