# Generated by Django 5.2.4 on 2026-01-02 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingsystem', '0004_alter_itemactivity_change_alter_itemactivity_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemactivity',
            name='type',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
