# Generated by Django 5.2.7 on 2025-11-24 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billingsystem", "0004_merge_20251124_0849"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Books",
        ),
    ]
