# Generated by Django 5.2.4 on 2025-12-02 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billingsystem', '0004_product_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_quantity',
        ),
    ]
