# Generated by Django 5.2.4 on 2025-12-16 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingsystem', '0004_remove_ordersummary_additional_charges_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemainingAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='billingsystem.customer')),
            ],
        ),
    ]
