# Generated by Django 5.2.4 on 2026-01-19 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billingsystem', '0004_customer_opening_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='opening_type',
        ),
    ]
