# Generated by Django 5.2.4 on 2025-12-19 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingsystem', '0004_rename_customero_remainingamount_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remainingamount',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('pan_id', models.CharField(blank=True, max_length=15)),
                ('address', models.CharField(blank=True, max_length=15)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='billingsystem.company')),
            ],
        ),
    ]
