# Generated by Django 5.2.4 on 2026-01-24 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingsystem', '0004_remove_purchase_additional_charge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersummary',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='billingsystem.orderlist'),
        ),
    ]
