# Generated by Django 5.2.4 on 2025-12-16 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingsystem', '0005_remainingamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalcharges',
            name='additional_charges',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='billingsystem.orderlist'),
        ),
    ]
