# Generated by Django 5.2.7 on 2025-12-20 05:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billingsystem", "0005_alter_remainingamount_remaining_amount_supplier"),
    ]

    operations = [
        migrations.AddField(
            model_name="remainingamount",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="remainingamount",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="remaining_amounts",
                to="billingsystem.orderlist",
            ),
        ),
        migrations.AddField(
            model_name="remainingamount",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="remainingamount",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="remaining_amounts",
                to="billingsystem.customer",
            ),
        ),
    ]
