# Generated by Django 5.2.7 on 2025-12-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "billingsystem",
            "0005_bill_description_orderlist_invoice_description_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="phone",
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
