# Generated by Django 5.2.4 on 2026-01-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingsystem', '0005_itemactivity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemactivity',
            name='change',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='itemactivity',
            name='type',
            field=models.CharField(max_length=200),
        ),
    ]
