# Generated by Django 5.2.7 on 2025-12-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "billingsystem",
            "0006_remainingamount_created_at_remainingamount_order_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="additionalcharges",
            old_name="additional_charges",
            new_name="order",
        ),
        migrations.AlterField(
            model_name="additionalcharges",
            name="additional_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
