# Generated by Django 5.2.7 on 2025-12-02 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billingsystem", "0006_customer_phone"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="customer",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="customer",
            name="email",
        ),
    ]
