# Generated by Django 5.2.4 on 2026-01-05 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingsystem', '0006_alter_itemactivity_change_alter_itemactivity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemactivity',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
