# Generated by Django 5.2.7 on 2025-12-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billingsystem", "0007_alter_customer_unique_together_remove_customer_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="address",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="customer",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="customer",
            name="pan_id",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name="customer",
            unique_together={("email",)},
        ),
    ]
