# Generated by Django 5.2.7 on 2025-12-20 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "billingsystem",
            "0007_rename_additional_charges_additionalcharges_order_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderlist",
            name="company",
        ),
        migrations.RemoveField(
            model_name="orderlist",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="orderlist",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="orderlist",
            name="invoice_description",
        ),
        migrations.RemoveField(
            model_name="orderlist",
            name="is_simple_invoice",
        ),
        migrations.RemoveField(
            model_name="orderlist",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="orderlist",
            name="order_date",
        ),
        migrations.RemoveField(
            model_name="orderlist",
            name="payment_status",
        ),
    ]
