# Generated by Django 5.2.4 on 2026-01-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingsystem', '0007_alter_itemactivity_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='low_stock_bar',
            field=models.IntegerField(default=0),
        ),
    ]
