# Generated by Django 5.2.7 on 2026-01-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billingsystem", "0008_product_low_stock_bar"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="discount",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
