# Generated by Django 5.2.7 on 2025-12-03 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "billingsystem",
            "0008_customer_address_customer_email_customer_pan_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="customer",
            unique_together=set(),
        ),
    ]
