# Generated by Django 5.2.7 on 2025-12-20 12:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "billingsystem",
            "0008_remove_orderlist_company_remove_orderlist_created_by_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="additionalcharges",
            old_name="order",
            new_name="additional_charges",
        ),
        migrations.RemoveField(
            model_name="remainingamount",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="remainingamount",
            name="order",
        ),
        migrations.RemoveField(
            model_name="remainingamount",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="orderlist",
            name="company",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="billingsystem.company",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderlist",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="orderlist",
            name="customer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="billingsystem.customer",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderlist",
            name="invoice_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderlist",
            name="is_simple_invoice",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="orderlist",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderlist",
            name="order_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="orderlist",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("UNPAID", "Unpaid"),
                    ("PARTIAL", "Partial"),
                    ("PAID", "Paid"),
                ],
                default="UNPAID",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="additionalcharges",
            name="additional_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="remainingamount",
            name="customer",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer",
                to="billingsystem.customer",
            ),
        ),
    ]
