# Generated by Django 5.2.4 on 2026-01-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingsystem', '0009_bill_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
