# Generated by Django 5.2.4 on 2025-12-04 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingsystem', '0009_alter_customer_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
