# Generated by Django 5.2.7 on 2025-12-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "billingsystem",
            "0009_rename_order_additionalcharges_additional_charges_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="ordersummary",
            name="due_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
