# Generated by Django 5.2.7 on 2025-12-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billingsystem", "0010_ordersummary_due_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="sabina",
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
