# Generated by Django 5.2.7 on 2026-01-07 16:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billingsystem", "0011_alter_ordersummary_discount_alter_ordersummary_tax"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderlist",
            name="uid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
