# Generated by Django 5.2.7 on 2025-12-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billingsystem", "0011_user_sabina"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="sahil",
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
