# Generated by Django 5.2.7 on 2026-01-08 13:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billingsystem", "0012_orderlist_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderlist",
            name="uid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
