# Generated by Django 5.2.7 on 2025-12-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billingsystem", "0012_user_sahil"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bibek",
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
