# Generated by Django 5.2.7 on 2025-12-21 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billingsystem", "0013_user_bibek"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="bibek",
        ),
        migrations.RemoveField(
            model_name="user",
            name="sabina",
        ),
        migrations.RemoveField(
            model_name="user",
            name="sahil",
        ),
    ]
