# Generated by Django 5.2.4 on 2025-12-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingsystem', '0014_remove_user_bibek_remove_user_sabina_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sahil',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
