# Generated by Django 5.2.4 on 2025-12-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingsystem', '0015_user_sahil'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='drag',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
