# Generated by Django 5.2.7 on 2025-12-21 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billingsystem", "0016_user_drag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="drag",
        ),
        migrations.RemoveField(
            model_name="user",
            name="sahil",
        ),
    ]
