from django.urls import path

from . import views

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("invoice-uid/<int:id>/",views.invoice_uid,name="invoice_uid"),
    path("fetch-activity/<uuid:id>/", views.fetch_product_activities, name="fetch-activity"),
    path("fetch-transactions/<uuid:id>/",views.fetch_transactions,name="fetch_transactions"),
    path('fetch-all-transactions/',views.fetch_all_transactions,name="fetch_all_transactions"),
    path("payment-in/<int:id>/",views.payment_in,name="payment_in"),
    path("payment-out/<int:id>/",views.payment_out,name="payment_out"),
    path("balance-adjustment/<int:id>/",views.balance_adjustment,name="balance_adjustment"),
    path("update-stock/<int:id>/", views.update_stock, name="update_stock"),
    path("products-json/", views.products_json, name="products_json"),
    path("category-json/", views.category_json, name="category_json"),
    path("filtered-products/", views.filtered_products, name="filtered_products"),
    path("product-detail/", views.product_detail, name="product_detail"),
    path("product-detail/<uuid:id>/", views.product_detail, name="product_detail"),
    path("clients-json/", views.clients_json, name="clients_json"),
    path("clients-info/<uuid:id>/", views.client_info_payment_id, name="client_info_payment_id"),
    path("client-detail/", views.client_detail, name="client_detail"),
    path("client-detail/<uuid:id>/", views.client_detail, name="client_detail"),
    path("client-update/<int:id>/",views.update_client,name="update_client"),
    path("update-opening/<uuid:id>/",views.update_opening_balance,name="update_opening_balance"),
    path("update-payment_in/<int:id>/",views.update_payment_in,name="update_payment_in"),
    path("update-payment-out/<int:id>/",views.update_payment_out,name="update_payment_out"),
    path("fill-payment-in-modal/<int:id>/",views.fill_update_payment_modal,name="fill_update_payment_modal"),
    path("fill-payment-out-modal/<int:id>/",views.fill_update_payment_out_modal,name="fill_update_payment_out_modal"),
    path("update-add-adjust/<int:id>/",views.update_add_adjust,name="update_add_adjust"),
    path("fill-up-add-adjust/<int:id>/",views.fill_up_add_adjust,name="fill_up_add_adjust"),
    path("update-reduce-adjust/<int:id>/",views.update_reduce_adjust,name="update_reduce_adjust"),
    path("save-product/", views.save_product, name="save_product"),
    path("update-product/<int:id>/", views.update_product, name="update_product"),
    path("delete-product/<int:id>/", views.delete_product, name="delete_product"),
    path("add-stock/<int:id>/", views.add_stock, name="add-stock"),
    path("reduce-stock/<int:id>/", views.reduce_stock, name="reduce-stock"),
    path("save-invoice/", views.save_invoice, name="save_invoice"),
    path("save-customer/",views.save_customer,name="save_customer"),
    path("delete_invoice/<int:id>/", views.delete_invoice, name="delete_invoice"),
    path("invoice-layout/<uuid:id>/", views.invoice_layout, name="invoice_layout"),
    path("invoices/", views.invoices, name="invoices"),
    path("invoices/<uuid:id>/", views.invoices, name="invoices"),
    path(
        "products/", views.products, name="products"
    ),  # FIXED: views.products not views.Product
    path("clients/", views.clients, name="clients"),
    path("reports/", views.reports, name="reports"),
    path("settings/", views.settings, name="settings"),
    path("expenses/",views.expenses,name="expenses"),
    path("purchase/",views.purchase,name="purchase"),
    path("expense-category/",views.expense_category,name="expense_category"),
    path("save-category/",views.save_category,name="save_category"),
    path("expense-info/",views.expense_info,name="expense_info"),
    path("expense-info/<int:id>/",views.expense_info,name="expense_info"),
    path("save-expenses/",views.save_expenses,name="save_expenses"),
    path("update-expense/<int:id>/",views.update_expense,name = "update_expense"),
    path("delete-expense/<int:id>/",views.delete_expense,name="delete_expense"),
    path("save-client/", views.save_client, name="save_client"),
    path("delete-client/<int:id>/",views.delete_client,name="delete_client"),
    path("create-invoice/", views.create_invoice_page, name="create_invoice_page"),
    path("purchase/create/",views.create_purchases,name="create_purchase"),
    path("customer-totals/",views.customer_totals,name="customer_totals"),
]
